// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2G_apCpMsfHZlbx-jmrjGBWjzsMGr5a8',
    appId: '1:438637721191:web:66c5dd43a976036b3906c2',
    messagingSenderId: '438637721191',
    projectId: 'fire-3cf46',
    authDomain: 'fire-3cf46.firebaseapp.com',
    storageBucket: 'fire-3cf46.firebasestorage.app',
    measurementId: 'G-S6J4CVX846',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgKDKI0fQmsXsa-1e0z4EwE7FGnZSMeM8',
    appId: '1:438637721191:android:e9f68241bf4ec34e3906c2',
    messagingSenderId: '438637721191',
    projectId: 'fire-3cf46',
    storageBucket: 'fire-3cf46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEsQQa31Qe9Nm24wKirjPUJ33p_uFmwGs',
    appId: '1:438637721191:ios:fbe610dcabbe4a7a3906c2',
    messagingSenderId: '438637721191',
    projectId: 'fire-3cf46',
    storageBucket: 'fire-3cf46.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEsQQa31Qe9Nm24wKirjPUJ33p_uFmwGs',
    appId: '1:438637721191:ios:fbe610dcabbe4a7a3906c2',
    messagingSenderId: '438637721191',
    projectId: 'fire-3cf46',
    storageBucket: 'fire-3cf46.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2G_apCpMsfHZlbx-jmrjGBWjzsMGr5a8',
    appId: '1:438637721191:web:2cb6723ebf6be7533906c2',
    messagingSenderId: '438637721191',
    projectId: 'fire-3cf46',
    authDomain: 'fire-3cf46.firebaseapp.com',
    storageBucket: 'fire-3cf46.firebasestorage.app',
    measurementId: 'G-0P7S1BE59G',
  );
}
